version: '3.4'

services:
  webpack_app:
    container_name: webpack_app
    image: liangwuxu/webpack_app:2.0
    volumes:
      - db-data:/etc/data
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
volumes:
  db-data: